// Assuming 'Inter' is a simple function for demonstration purposes
function Inter(options) {
  const { subsets } = options;
  const className = `inter-${subsets.join('-')}`;
  return {
    className,
  };
}

// Import React if not already imported
import React from 'react';

// Assuming 'metadata' is used for something else, it's retained in the export
const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Corrected RootLayout React component
function RootLayout({ children }) {
  const inter = Inter({ subsets: ['latin'] });
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

// Export the corrected components
export { metadata, RootLayout };
